### ISSUE TITLE
RuboCop v1.70 incompatibilities and new RuboCop add-on

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#3046]
RuboCop v1.70 added an [add-on to provide linting and formatting via the Ruby LSP](https://github.com/rubocop/rubocop/pull/13628). This is a great move long term, as it allows RuboCop maintainers to improve the integrations and ensure compatibility across versions.

Unfortunately, this first iteration of the add-on is conflicting with our internal integrations with RuboCop and may cause some issues. Namely, two things may happen:

1. Namespace conflicts like #3044
2. Linter registration conflicts since it's using the same identifier as the one we use internally. This means that the LSP may end up using the add-on version and some features can potentially be missing or other features may break (like watching .rubocop.yml)

### Transition plan

We need a transition plan since people will still rely on our internal integrations while they are upgrading RuboCop. It may take a while until the community catches up to the newest versions.

Steps

- [ ] Decide identifier change. If we change ours from `rubocop` to `rubocop_internal`, it will avoid the conflict, but it also means that anyone who has configured to use `rubocop` will try to use the add-on. If the application is on an older version of RuboCop where the add-on is not available, that will fail and no formatting will be available. We can add logic to check for this scenario and try to do the right thing depending on what's available
- [ ] Our automatic detection for linters will need to change as well. We will now need to take the add-on into account if it's available and then decide whether to use the internal or the add-on version
- [ ] Map all feature differences between our internal integrations and the RuboCop add-on, so that we can ensure feature completeness for the community

**Comment by vinistock** [comment]
#3045 fixed the namespace conflicts.

**Comment by Earlopain** [comment]
Do you still think this should be reverted for now? I haven't tried it out myself yet, so no idea what the impact is.

Most of the PR is good, just removing the addon itself to give more time shouldn't be too big of a ask I think.

**Comment by vinistock** [comment]
No longer necessary after #3045. It seems like things are working normally, although we still need to iron out the remaining details. I updated my comment on the RuboCop PR.

**Comment by vinistock** [comment]
The releases were cut today https://github.com/Shopify/ruby-lsp/releases/tag/v0.23.6 and https://github.com/Shopify/ruby-lsp/releases/tag/vscode-ruby-lsp-v0.8.18.

**Comment by mtrepanier** [comment]
Yes it just appeared in the VsCode marketplace.  But even by choosing `rubocop_internal` instead of `auto` or `rubocop` I have same error

```Error running diagnostics: uninitialized constant RubyLsp::RuboCop::Cop```

**Comment by mtrepanier** [comment]
I uninstalled all `ruby-lsp` gem and related and did install the latest and still have same issue.

After uninstall
```
> gem list ruby-lsp


*** LOCAL GEMS ***

```

After re-install latest
```
> gem list ruby-lsp

*** LOCAL GEMS ***

ruby-lsp (0.23.6, 0.11.2)
ruby-lsp-rails (0.2.6)
```

**Comment by vinistock** [comment]
The version that runs the server is specified in the bundle composed under the `.ruby-lsp` directory. Did you run the `Update language server gem` command or `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle update ruby-lsp` to trigger an update for the version currently locked as mentioned in the those outdated docs?

It using those techniques is not working, then some dependency of your app may be constraining the update, which is also explained in those docs.

**Comment by andyw8** [comment]
@bradsb please check your Bundler version is up-to-date. IIRC some older versions had problem with resolving to incorrect sources.

**Comment by celinefb** [comment]
I am running into the same issue. RubyLSP does not index anymore in one of my projects that is using Rubocop 1.70.0 and Standard 1.44.0

**Comment by dmoore1989** [comment]
I'm also still seeing the same error in my environment (`uninitialized constant RubyLsp::RuboCop::Cop`). I ran `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle update ruby-lsp`, which said the version stayed the same. Using ruby-lsp@0.23.6 in Neovim.

**Comment by dmoore1989** [comment]
@vinistock I'm actually seeing v0.17.16.  It looks like ruby-lsp-rails is limiting it to `(>= 0.17.12, < 0.18.0)`

**Comment by 1990eam** [comment]
Hey. I'm trying to update the server version from 0.17.2 to the latest one to fix this issue, but I get this in the Vscode output console. 

Could you confirm if it's not being updated due to the stated "Unresolved or ambiguous specs" warning?

`2025-01-27 15:21:58.122 [info] (arda) WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      language_server-protocol (~> 3.17.0)

 Available/installed versions of this gem:
      - 3.17.0.4
      - 3.17.0.3


 logger (>= 0)

Available/installed versions of this gem:
      - 1.6.5
      - 1.6.4
      - 1.6.3
      - 1.6.1
      - 1.6.0
      - 1.5.3

2025-01-27 15:21:58.935 [info] (arda) Fetching gem metadata from https://rubygems.org/

2025-01-27 15:22:00.429 [info] (arda) Resolving dependencies...

2025-01-27 15:22:01.574 [info] (arda) WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)

Available/installed versions of this gem:
      - 3.1.2
      - 3.0.4

WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.

2025-01-27 15:22:01.676 [info] (arda) Fetching rbs 2.8.4

2025-01-27 15:22:02.649 [info] (arda) Installing rbs 2.8.4 with native extensions

2025-01-27 15:22:04.647 [info] (arda) Bundle complete! 102 Gemfile dependencies, 307 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

2025-01-27 15:22:04.648 [info] (arda) 3 installed gems you directly depend on are looking for funding.
  Run `bundle fund` for details

2025-01-27 15:22:04.649 [info] (arda) Ruby LSP> Composed bundle installation complete

2025-01-27 15:22:04.849 [info] (arda) Composed Bundle set up successfully

2025-01-27 15:22:05.741 [info] (arda) Initializing Ruby LSP v0.17.2...`

**Comment by axsuul** [comment]
I think I'm running into this issue. Is there any way in the meantime to ignore the add-on from Rubocop?

**Comment by MattSNZ** [comment]
I'm having the same issue when I try start the server, though when I attempt to upgrade it all I get is this error:

```
[error] (reponame) Error restarting the server: Cannot read properties of undefined (reading 'compose_bundle')
```

I've bumped `rbs ` to 3.9.2 but that hasn't fixed it. Any ideas?

**Comment by whoisahmed** [comment]
@vinistock Any update on this, please? I'm getting this error too.

**Comment by vinistock** [comment]
@whoisahmed which error?

**Comment by whoisahmed** [comment]
`uninitialized constant RubyLsp::RuboCop::Cop`

**Comment by vinistock** [comment]
Are you on the latest version of the Ruby LSP server? That issue should be fixed already since #3044.

**Comment by whoisahmed** [comment]
@vinistock  yes
```
ruby-lsp -v
0.26.1
```

**Comment by whoisahmed** [comment]
maybe vscode is using other version, how can I update it please?

**Comment by whoisahmed** [comment]
@vinistock thanks, I upgraded and its working now.

**Comment by brevio-nicolay** [comment]
Is this supposed to be fixed? I'm running the latest version of the VSCode addon and this error still pops up for me.

<img width="582" height="1095" alt="Image" src="https://github.com/user-attachments/assets/b67a72fb-b06b-4904-b3e1-f697f028865c" />

**Comment by janko** [comment]
FWIW I'm not experiencing these errors anymore.
